cd code
echo Generating synthetic data...
Rscript generate_synthetic_data.R
echo Plotting synthetic data....
Rscript plot_data.R 'syn'
echo Running abc...
Rscript simulate_samples.R 'syn'
Rscript calc_summary_stats.R 'syn'
echo Plotting results....
Rscript plot_abc_results.R 'syn'
cd ..